@protocol IPosition, IVelocity, IMovable;
@protocol IRadius, IParticleColider, IParticle;
@protocol IHalfPlaneColider, IAxisAlignedHalfPlaneCollider;
@protocol IMass;
@protocol ICoefficientOfRestition;
@protocol ILifetime;
@protocol IRectangleDimensions;
@protocol IRectangleCollider;
@protocol IAxisAlignedRectangleCollider;
@protocol ICustomCollider;
@protocol ISceneUser;
@class Lifetime;
