@protocol IPosition, IVelocity, IMovable;
@protocol IRadius, IParticleColider, IParticle;
@protocol IHalfPlaneColider, IAxisAlignedHalfPlaneCollider;
@protocol IMass;
@protocol ICoefficientOfRestition;
@protocol ILifetime;
@protocol IDimensions;
@protocol IBoundingBoxCollider;
@protocol IBoundingBox;
@class Lifetime;
